/**
 * Type definitions for AI-generated outputs across all LexAI features.
 *
 * Covers: document summaries, Q&A chat messages, next-step recommendations,
 * document comparison results, and the attorney-pack question generator.
 */

// ---------------------------------------------------------------------------
// Summary
// ---------------------------------------------------------------------------

/**
 * A single labeled section within an AI-generated document summary.
 *
 * @property title   - Section heading (e.g., "Key Obligations", "Termination Conditions").
 * @property content - The AI-generated text for this section, written at Flesch-Kincaid ≤ grade 8.
 */
export interface SummarySection {
  /** Section heading displayed above the content block. */
  title: string;
  /** AI-generated section text written in plain language (Flesch-Kincaid ≤ grade 8). */
  content: string;
}

/**
 * The complete summary result for a single document, returned by the `/api/summarize` route.
 *
 * @property documentId  - ID of the document this summary was generated for.
 * @property sections    - Ordered array of labeled summary sections.
 * @property disclaimer  - Legal disclaimer appended to every AI-generated summary.
 * @property generatedAt - Unix timestamp (ms) when the summary was completed.
 */
export interface SummaryResult {
  /** ID of the document this summary was generated for. */
  documentId: string;
  /** Ordered array of labeled summary sections. */
  sections: SummarySection[];
  /** Legal disclaimer text appended to every AI-generated summary. */
  disclaimer: string;
  /** Unix timestamp (milliseconds) when the summary generation completed. */
  generatedAt: number;
}

// ---------------------------------------------------------------------------
// Q&A Chat
// ---------------------------------------------------------------------------

/**
 * A single message in the document Q&A chat interface.
 *
 * @property id              - Client-generated UUID uniquely identifying this message.
 * @property role            - Who authored the message: `'user'` or `'assistant'`.
 * @property content         - The message text.
 * @property confidenceScore - AI confidence (0–100) in the answer; only present on assistant messages.
 * @property citation        - Exact clause text the answer was derived from, or `null` if not applicable.
 * @property isLowConfidence - `true` when `confidenceScore` is below the low-confidence threshold (e.g., < 40).
 * @property timestamp       - Unix timestamp (ms) when the message was created.
 */
export interface QAMessage {
  /** Client-generated UUID uniquely identifying this message in the conversation. */
  id: string;
  /** Message author: `'user'` for questions, `'assistant'` for AI responses. */
  role: 'user' | 'assistant';
  /** The full text content of the message. */
  content: string;
  /** AI confidence score (0–100) for this answer. Only present on assistant messages. */
  confidenceScore?: number;
  /** Exact clause text cited as the source of the answer, or `null` if no citation applies. */
  citation?: string | null;
  /** `true` when the confidence score falls below the low-confidence display threshold. */
  isLowConfidence?: boolean;
  /** Unix timestamp (milliseconds) recorded when this message was created. */
  timestamp: number;
}

/**
 * A condensed message history item forwarded to the Gemini API as conversation context.
 *
 * Strips UI-only fields (id, confidenceScore, citation, etc.) before sending to the server.
 *
 * @property role    - `'user'` or `'assistant'`.
 * @property content - The message text.
 */
export interface QAHistoryItem {
  /** Message author role, matching Gemini's expected conversation format. */
  role: 'user' | 'assistant';
  /** Message content text forwarded to the model as conversation history. */
  content: string;
}

// ---------------------------------------------------------------------------
// Next Steps
// ---------------------------------------------------------------------------

/**
 * A single recommended action item generated by the `/api/next-steps` route.
 *
 * @property id              - Client-generated UUID for this step.
 * @property text            - Plain-language description of the action to take.
 * @property category        - Urgency bucket: `'Do Now'`, `'Do Soon'`, or `'Optional'`.
 * @property isTimeSensitive - `true` when the step has an extractable deadline.
 * @property deadline        - ISO 8601 date string if a specific deadline was found in the document, or `null`.
 */
export interface NextStep {
  /** Client-generated UUID uniquely identifying this next step. */
  id: string;
  /** Plain-language description of the recommended action. */
  text: string;
  /** Urgency category used for grouping and visual priority. */
  category: 'Do Now' | 'Do Soon' | 'Optional';
  /** `true` when a concrete deadline was extracted from the document for this step. */
  isTimeSensitive: boolean;
  /** ISO 8601 date string for the deadline, or `null` if no specific date applies. */
  deadline?: string | null;
}

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

/**
 * A single highlighted difference or conflict found between two compared documents.
 *
 * @property type               - The kind of discrepancy: `'conflict'`, `'missing'`, or `'difference'`.
 * @property clauseText         - The relevant clause text from the primary document.
 * @property matchedClauseText  - The corresponding clause text from the comparison document, if applicable.
 * @property summary            - AI-generated plain-language explanation of the discrepancy.
 * @property documentName       - Name of the document where this highlight appears.
 */
export interface ComparisonHighlight {
  /** The category of discrepancy found between the two documents. */
  type: 'conflict' | 'missing' | 'difference';
  /** The clause text from the document being highlighted. */
  clauseText: string;
  /** The corresponding clause text from the other document, if a match was found. */
  matchedClauseText?: string;
  /** AI-generated plain-language summary of what this difference means. */
  summary: string;
  /** Display name of the document this highlight belongs to. */
  documentName?: string;
}

/**
 * The complete comparison result returned by the `/api/compare` route.
 *
 * `highlights` is a tuple where index 0 contains highlights for document A
 * and index 1 contains highlights for document B.
 *
 * @property highlights        - Tuple of highlight arrays, one per document.
 * @property totalDifferences  - Total count of `'difference'` type highlights across both documents.
 * @property totalConflicts    - Total count of `'conflict'` type highlights across both documents.
 * @property totalMissing      - Total count of `'missing'` type highlights across both documents.
 */
export interface ComparisonResult {
  /** Tuple of highlight arrays: index 0 = document A highlights, index 1 = document B highlights. */
  highlights: [ComparisonHighlight[], ComparisonHighlight[]];
  /** Total number of general differences found across both documents. */
  totalDifferences: number;
  /** Total number of direct conflicts found between the two documents. */
  totalConflicts: number;
  /** Total number of clauses present in one document but absent in the other. */
  totalMissing: number;
}

// ---------------------------------------------------------------------------
// Attorney Pack
// ---------------------------------------------------------------------------

/**
 * One of the four fixed headings used to group questions in the Attorney Pack.
 *
 * @property key   - Machine-readable kebab-case identifier used as a `Record` key.
 * @property label - Human-readable heading label displayed in the UI.
 */
export interface AttorneyHeading {
  /** Machine-readable kebab-case key used to index into `questionsByHeading`. */
  key: 'understanding-rights' | 'clarifying-obligations' | 'identifying-risks' | 'before-signing';
  /** Human-readable label displayed as the section heading in the Attorney Pack UI. */
  label: string;
}

/**
 * The complete Attorney Pack data payload generated by the `/api/attorney-pack` route.
 *
 * Contains 8–15 document-specific questions organized under four standard headings,
 * intended to help users prepare for a consultation with a licensed attorney.
 *
 * @property documentId         - ID of the document these questions were generated for.
 * @property headings           - Ordered array of the four attorney pack section headings.
 * @property questionsByHeading - Map from heading `key` to the list of questions for that section.
 * @property disclaimer         - Legal disclaimer reminding users this is not legal advice.
 * @property totalQuestions     - Total number of questions across all headings.
 */
export interface AttorneyPackData {
  /** ID of the document these questions were generated for. */
  documentId: string;
  /** Ordered array of the four standard attorney pack section headings. */
  headings: AttorneyHeading[];
  /** Map from heading `key` to the list of generated questions for that heading. */
  questionsByHeading: Record<string, string[]>;
  /** Legal disclaimer reminding users that this pack does not constitute legal advice. */
  disclaimer: string;
  /** Total question count across all headings (should be 8–15). */
  totalQuestions: number;
}
