/**
 * Type definitions for the AI-generated document review checklist feature.
 *
 * The checklist is organized under four fixed headings and each entry
 * tracks its own checked state for interactive toggling in the UI.
 */

// ---------------------------------------------------------------------------
// ChecklistHeading
// ---------------------------------------------------------------------------

/**
 * The four fixed section headings used to organize checklist entries.
 *
 * - `'Your Obligations'`                  — Actions or duties the signer is required to perform.
 * - `'Your Rights'`                       — Entitlements and protections afforded to the signer.
 * - `'Important Deadlines'`               — Time-sensitive dates or notice periods found in the document.
 * - `'Actions Required Before Signing'`   — Steps the signer should take or verify before executing the agreement.
 */
export type ChecklistHeading =
  | 'Your Obligations'
  | 'Your Rights'
  | 'Important Deadlines'
  | 'Actions Required Before Signing';

// ---------------------------------------------------------------------------
// ChecklistEntry
// ---------------------------------------------------------------------------

/**
 * A single item within a checklist section.
 *
 * @property id         - Client-generated UUID uniquely identifying this checklist entry.
 * @property text       - Plain-language description of the obligation, right, deadline, or action.
 * @property clauseRef  - Optional reference to the originating clause ID, or `null` if not applicable.
 * @property checked    - Whether the user has marked this item as complete or reviewed.
 */
export interface ChecklistEntry {
  /** Client-generated UUID uniquely identifying this entry within the checklist. */
  id: string;
  /** Plain-language description of the item, written at an accessible reading level. */
  text: string;
  /** ID of the originating clause in the document, or `null` if no specific clause applies. */
  clauseRef?: string | null;
  /** Whether the user has toggled this item as reviewed/complete. Defaults to `false`. */
  checked: boolean;
}

// ---------------------------------------------------------------------------
// ChecklistData
// ---------------------------------------------------------------------------

/**
 * The complete checklist data payload generated by the `/api/checklist` route
 * and stored in the Zustand session store.
 *
 * @property documentId  - ID of the document this checklist was generated for.
 * @property items       - Map from each `ChecklistHeading` to its ordered array of entries.
 * @property generatedAt - Unix timestamp (ms) when the checklist was generated.
 */
export interface ChecklistData {
  /** ID of the document this checklist was generated for. */
  documentId: string;
  /** Checklist entries grouped by their section heading. */
  items: Record<ChecklistHeading, ChecklistEntry[]>;
  /** Unix timestamp (milliseconds) recorded when the checklist generation completed. */
  generatedAt: number;
}
